apiVersion: v1
kind: Pod
metadata:
  name: multi-pod
  labels:
    app: multi-pod
spec:
  containers:
    - name: nginx-container
      image: nginx
      volumeMounts: # 声明卷挂载
        - mountPath: /usr/share/nginx/html
          name: nginxVolume
    - name: alpine-container
      image: alpine
      command:
        - /bin/sh
        - -c
        - while true; do sleep 1 ;echo $(date "+%Y%m%d-%H%M%S") > /app/index.html ;done
      volumeMounts:
        - mountPath: /app
          name: nginxVolume
  volumes:
    - name: nginxVolume
      emptyDir: {} # 相当于 Docker 中的匿名挂载，会在外部创建一个位置
  restartPolicy: Always